version: '2'
services:
  helen:
    image: tf2stadium/helen:dev
    restart: always
    depends_on:
      - database
      - rabbitmq
      - pauling
      - fumble
    env_file: env/helen-dev.env

    ports:
      - "4001:80"
      - "4002:81"
    entrypoint: /bin/helen -disable_pauling=false -disable_fumble=false
    stop_signal: SIGTERM

  pauling:
    image: tf2stadium/pauling:dev
    restart: always
    stop_signal: SIGTERM
    depends_on:
      - database
      - rabbitmq
    ports:
      - "4003:4003/udp"
    env_file: env/pauling-dev.env

  frontend:
    image: tf2stadium/frontend:dev
    depends_on:
      - helen
    env_file: env/frontend-dev.env
    ports:
      - "4004:80"

  fumble:
     image: tf2stadium/fumble:dev
     restart: always
     depends_on:
       - database
       - murmur
       - rabbitmq
     env_file: env/fumble-dev.env

  database:
     env_file: env/database-dev.env
     volumes:
       - ./data/database_dev/data:/var/lib/postgresql/data

  murmur:
    ports:
      - "74738:64738/tcp"
      - "74738:74739/udp"
    volumes:
      - ./data/murmur_dev/:/data